#
name: Docker Image CI

# Configures this workflow to run every time a change is pushed to the
# branch called `main`.
on:
  push:
    tags:
      - '*.*.*'
    branches:
      - 'main'

# Defines two custom environment variables for the workflow. These are used
# for the Container registry domain, and a name for the Docker image that
# this workflow builds.

# There is a single job in this workflow. It's configured to run on the
# latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions 
    # in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker Image  
        run: docker build --platform linux/amd64 . -t registry.cn-hangzhou.aliyuncs.com/dbsnolimit/puter:latest
        timeout-minutes: 60
      - name: Login To Aliyun Docker Registry 
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Push Docker Image to aliyun docker registry   
        run: docker push registry.cn-hangzhou.aliyuncs.com/dbsnolimit/puter:latest
        timeout-minutes: 20
